name: 上班

on:
  workflow_dispatch:
  schedule:
    - cron: "30 06 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Install dependencies
        env:
          COMPOSER_AUTH: |
            {
              "github-oauth": {
                "github.com": "${{ secrets.GITHUB_TOKEN }}"
              }
            }
        run: composer install --no-dev --optimize-autoloader

      - name: Run sign
        env:
          MOGUDING_DEVICE: ${{ secrets.DEVICE }}
          MOGUDING_PHONE: ${{ secrets.PHONE }}
          MOGUDING_PASSWORD: ${{ secrets.PASSWORD }}
          MOGUDING_PROVINCE: ${{ secrets.PROVINCE }}
          MOGUDING_CITY: ${{ secrets.CITY }}
          MOGUDING_ADDRESS: ${{ secrets.ADDRESS }}
          MOGUDING_LONGITUDE: ${{ secrets.LONGITUDE }}
          MOGUDING_LATITUDE: ${{ secrets.LATITUDE }}
          MOGUDING_TYPE: "START"
          MOGUDING_DESCRIPTION: ${{ secrets.DESCRIPTION }}
          MOGUDING_SCT_KEY: ${{ secrets.SENDKEY }}
        run: php artisan moguding
